/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SubscribeForm = {
  _type: "subscribeForm";
  enabled?: boolean;
  label?: string;
  placeholder?: string;
  helpMessage?: string;
  successMessage?: string;
};

export type LensOptions = {
  _type: "lensOptions";
  category: string;
  options?: Array<{
    _key: string;
  } & LensOption>;
};

export type LensOption = {
  _type: "lensOption";
  title: string;
  altTitle?: string;
  description?: string;
  price: number;
  basePrice?: number;
  id?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type FooterTextItem = {
  _type: "footerTextItem";
  text: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  heading: string;
  items?: Array<{
    _key: string;
  } & InternalLink | {
    _key: string;
  } & Link | {
    _key: string;
  } & FooterTextItem>;
};

export type NavItem = {
  _type: "navItem";
  link?: InternalLink;
  children?: Array<{
    _key: string;
  } & InternalLink>;
};

export type SocialLink = {
  _type: "socialLink";
  platform: "instagram" | "tiktok";
  url: string;
};

export type InternalLink = {
  _type: "internalLink";
  label: string;
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
};

export type Link = {
  _type: "link";
  label: string;
  url?: string;
};

export type StoresSection = {
  _type: "storesSection";
  title?: string;
  stores?: Array<{
    title: string;
    subtitle?: string;
    address?: string;
    openingHours?: {
      monday?: string;
      tuesday?: string;
      wednesday?: string;
      thursday?: string;
      friday?: string;
      saturday?: string;
      sunday?: string;
    };
    phoneNumber?: string;
    externalLinks?: Array<{
      _key: string;
    } & Link>;
    _type: "store";
    _key: string;
  }>;
};

export type ListSection = {
  _type: "listSection";
  title?: string;
  layout?: "grid" | "column" | "row";
  items?: Array<{
    title: string;
    description?: string;
    link?: InternalLink;
    _type: "listItem";
    _key: string;
  }>;
};

export type TextSection = {
  _type: "textSection";
  title: string;
  description?: string;
  link?: InternalLink;
  textAlign?: "left" | "center" | "right";
};

export type ShopifyProductCarousel = {
  _type: "shopifyProductCarousel";
  collection: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collection";
  };
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  store?: {
    title?: string;
    id?: number;
    gid?: string;
    slug?: {
      current?: string;
    };
    imageUrl?: string;
    descriptionHtml?: string;
    isDeleted?: boolean;
    syncedAt?: string;
    createdAt?: string;
    disjunctive?: boolean;
    rules?: Array<{
      column?: string;
      condition?: string;
      relation?: string;
      _key: string;
    }>;
    shop?: {
      domain?: string;
    };
    sortOrder?: string;
  };
};

export type TabbedContent = {
  _type: "tabbedContent";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imagePosition?: "left" | "right";
  tabs?: Array<{
    title: string;
    description?: string;
    link?: InternalLink;
    _key: string;
  }>;
};

export type ImageWithContent = {
  _type: "imageWithContent";
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title: string;
  description?: string;
  listItems?: Array<string>;
  link?: InternalLink;
  imagePosition?: "left" | "right";
  layout?: "gap" | "joined";
};

export type Section = {
  _type: "section";
  title: string;
  description?: string;
  mediaType?: "image" | "video";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  aspectRatio?: "21:9" | "3:1" | "4:1";
  link?: InternalLink;
  contentPlacement?: "top" | "middle" | "bottom";
};

export type Carousel = {
  _type: "carousel";
  title?: string;
  cards?: Array<{
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title: string;
    description?: string;
    badge?: string;
    link?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    _type: "carouselCard";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  mediaType?: "image" | "video";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  title?: string;
  subtitle?: string;
  contentPlacement?: "left" | "right";
  aspectRatio?: "16:9" | "21:9";
  button?: {
    text?: string;
    url?: string;
  };
};

export type PageBuilder = Array<{
  _key: string;
} & Hero | {
  _key: string;
} & Carousel | {
  _key: string;
} & Section | {
  _key: string;
} & ImageWithContent | {
  _key: string;
} & TabbedContent | {
  _key: string;
} & ShopifyProductCarousel | {
  _key: string;
} & TextSection | {
  _key: string;
} & ListSection | {
  _key: string;
} & StoresSection>;

export type ProductConfiguration = {
  _id: string;
  _type: "productConfiguration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lensCategories?: Array<{
    _key: string;
  } & LensOptions>;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  valuesMessage?: string;
  columns?: Array<{
    _key: string;
  } & FooterColumn>;
  copyrightText?: string;
  showSocialLinks?: boolean;
  subscribeForm?: SubscribeForm;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navigation?: Array<{
    _key: string;
  } & NavItem>;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  announcementBar?: {
    enabled?: boolean;
    link?: InternalLink;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  siteUrl?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pathPrefix: "home" | "pages" | "collections";
  url?: Slug;
  content?: PageBuilder;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SubscribeForm | LensOptions | LensOption | Seo | FooterTextItem | FooterColumn | NavItem | SocialLink | InternalLink | Link | StoresSection | ListSection | TextSection | ShopifyProductCarousel | Collection | TabbedContent | ImageWithContent | Section | Carousel | Hero | PageBuilder | ProductConfiguration | Footer | Navigation | Header | SiteSettings | SanityImageCrop | SanityImageHotspot | Page | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries/footer.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0] {    valuesMessage,    columns[] {        _key,  heading,  items[] {    _type == "internalLink" => {        _key,  _type,  label,  internalLink->{    _id,    title,    pathPrefix,    "slug": url.current  }    },    _type == "link" => {        _key,  _type,  label,  url    },    _type == "footerTextItem" => {      _key,      _type,      text    }  }    },    copyrightText,    showSocialLinks,    subscribeForm {      heading,      description,      placeholder,      buttonText    }  }
export type FOOTER_QUERYResult = {
  valuesMessage: string | null;
  columns: Array<{
    _key: string;
    heading: string;
    items: Array<{
      _key: string;
      _type: "footerTextItem";
      text: string;
    } | {
      _key: string;
      _type: "internalLink";
      label: string;
      internalLink: {
        _id: string;
        title: string | null;
        pathPrefix: "collections" | "home" | "pages";
        slug: string | null;
      } | null;
    } | {
      _key: string;
      _type: "link";
      label: string;
      url: string | null;
    }> | null;
  }> | null;
  copyrightText: string | null;
  showSocialLinks: boolean | null;
  subscribeForm: {
    heading: null;
    description: null;
    placeholder: string | null;
    buttonText: null;
  } | null;
} | null;

// Source: ./sanity/lib/queries/header.ts
// Variable: HEADER_QUERY
// Query: *[_type == "header"][0] {    announcementBar {      enabled,      link {          _key,  _type,  label,  internalLink->{    _id,    title,    pathPrefix,    "slug": url.current  }      }    }  }
export type HEADER_QUERYResult = {
  announcementBar: {
    enabled: boolean | null;
    link: {
      _key: null;
      _type: "internalLink";
      label: string;
      internalLink: {
        _id: string;
        title: string | null;
        pathPrefix: "collections" | "home" | "pages";
        slug: string | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ./sanity/lib/queries/navigation.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"][0] {    navigation[] {        _key,  link {      _key,  _type,  label,  internalLink->{    _id,    title,    pathPrefix,    "slug": url.current  }  },  children[] {      _key,  _type,  label,  internalLink->{    _id,    title,    pathPrefix,    "slug": url.current  }  }    }  }
export type NAVIGATION_QUERYResult = {
  navigation: Array<{
    _key: string;
    link: {
      _key: null;
      _type: "internalLink";
      label: string;
      internalLink: {
        _id: string;
        title: string | null;
        pathPrefix: "collections" | "home" | "pages";
        slug: string | null;
      } | null;
    } | null;
    children: Array<{
      _key: string;
      _type: "internalLink";
      label: string;
      internalLink: {
        _id: string;
        title: string | null;
        pathPrefix: "collections" | "home" | "pages";
        slug: string | null;
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: ./sanity/lib/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    siteName,    siteUrl,    logo {        asset->{    _id,    url,    metadata {      lqip,      dimensions    }  },  hotspot,  crop,  alt    },    favicon {        asset->{    _id,    url,    metadata {      lqip,      dimensions    }  },  hotspot,  crop,  alt    },    seo {        metaTitle,  metaDescription,  ogImage {      asset->{    _id,    url,    metadata {      lqip,      dimensions    }  },  hotspot,  crop,  alt  },  noIndex    }  }
export type SITE_SETTINGS_QUERYResult = {
  siteName: string;
  siteUrl: string | null;
  logo: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: null;
  } | null;
  favicon: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"footer\"][0] {\n    valuesMessage,\n    columns[] {\n      \n  _key,\n  heading,\n  items[] {\n    _type == \"internalLink\" => {\n      \n  _key,\n  _type,\n  label,\n  internalLink->{\n    _id,\n    title,\n    pathPrefix,\n    \"slug\": url.current\n  }\n\n    },\n    _type == \"link\" => {\n      \n  _key,\n  _type,\n  label,\n  url\n\n    },\n    _type == \"footerTextItem\" => {\n      _key,\n      _type,\n      text\n    }\n  }\n\n    },\n    copyrightText,\n    showSocialLinks,\n    subscribeForm {\n      heading,\n      description,\n      placeholder,\n      buttonText\n    }\n  }\n": FOOTER_QUERYResult;
    "\n  *[_type == \"header\"][0] {\n    announcementBar {\n      enabled,\n      link {\n        \n  _key,\n  _type,\n  label,\n  internalLink->{\n    _id,\n    title,\n    pathPrefix,\n    \"slug\": url.current\n  }\n\n      }\n    }\n  }\n": HEADER_QUERYResult;
    "\n  *[_type == \"navigation\"][0] {\n    navigation[] {\n      \n  _key,\n  link {\n    \n  _key,\n  _type,\n  label,\n  internalLink->{\n    _id,\n    title,\n    pathPrefix,\n    \"slug\": url.current\n  }\n\n  },\n  children[] {\n    \n  _key,\n  _type,\n  label,\n  internalLink->{\n    _id,\n    title,\n    pathPrefix,\n    \"slug\": url.current\n  }\n\n  }\n\n    }\n  }\n": NAVIGATION_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0] {\n    siteName,\n    siteUrl,\n    logo {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions\n    }\n  },\n  hotspot,\n  crop,\n  alt\n\n    },\n    favicon {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions\n    }\n  },\n  hotspot,\n  crop,\n  alt\n\n    },\n    seo {\n      \n  metaTitle,\n  metaDescription,\n  ogImage {\n    \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions\n    }\n  },\n  hotspot,\n  crop,\n  alt\n\n  },\n  noIndex\n\n    }\n  }\n": SITE_SETTINGS_QUERYResult;
  }
}
